name: Clone and Push APT Repositories

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "CooperDActor-bytes"
        git config --global user.email "cooper@salty.cool"
        
    - name: Set up Git LFS
      run: |
        git lfs install

    - name: Clone Debian repository into "Debian" folder
      run: |
        # Clone the Debian repository into the "Debian" folder
        git clone --depth 1 http://deb.debian.org/debian ./apt-repos/Debian

    - name: Clone Ubuntu repository into "Ubuntu" folder
      run: |
        # Clone the Ubuntu repository into the "Ubuntu" folder
        git clone --depth 1 http://archive.ubuntu.com/ubuntu ./apt-repos/Ubuntu

    - name: Add, commit and push repositories
      run: |
        # Add all the new files in the cloned directories
        git add ./apt-repos/Debian ./apt-repos/Ubuntu
        
        # Commit the changes
        git commit -m "Clone Debian and Ubuntu APT repositories"

        # Push the changes to the GitHub repository
        git push origin HEAD
