name: Download and Push APT Repositories

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install wget
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Setup download directory
      run: |
        mkdir -p ./apt-repos/Debian
        mkdir -p ./apt-repos/Ubuntu

    - name: Download Debian APT repository files
      run: |
        # Download files from Debian repository (modify URL as needed)
        wget -r -np -nH --cut-dirs=3 -R "index.html*" -P ./apt-repos/Debian http://deb.debian.org/debian/dists/stable/main/binary-amd64/

    - name: Download Ubuntu APT repository files
      run: |
        # Download files from Ubuntu repository (modify URL as needed)
        wget -r -np -nH --cut-dirs=3 -R "index.html*" -P ./apt-repos/Ubuntu http://archive.ubuntu.com/ubuntu/dists/focal/main/binary-amd64/

    - name: Add, commit, and push files
      run: |
        # Add all the downloaded files
        git add ./apt-repos/

        # Commit the changes
        git commit -m "Add Debian and Ubuntu APT repository files"

        # Push the changes to the GitHub repository
        git push origin HEAD
