name: Download and Push APT Repositories

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget git apt-mirror

    - name: Clone the Debian mirror Git repository
      run: |
        git clone https://salsa.debian.org/mirror-team/archvsync.git ./apt-repos/Debian

    - name: Setup Ubuntu mirror configuration (using II Net Australia)
      run: |
        # Use sudo to create and configure apt-mirror list for Ubuntu
        echo "set base_path    /var/spool/apt-mirror" | sudo tee /etc/apt/mirror.list > /dev/null
        echo "deb http://mirror.internode.on.net/pub/ubuntu/ focal main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list > /dev/null
        echo "deb-src http://mirror.internode.on.net/pub/ubuntu/ focal main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list > /dev/null

    - name: Run apt-mirror to download Ubuntu repository
      run: |
        sudo apt-mirror

    - name: Add, commit, and push files
      run: |
        # Add the downloaded files (Debian and Ubuntu repos)
        git add ./apt-repos/

        # Commit the changes
        git commit -m "Add Debian and Ubuntu APT repository files"

        # Push the changes to the GitHub repository
        git push origin HEAD
