name: APT download

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git configuration
      run: |
        git config --global user.name "CooperDActor-bytes"
        git config --global user.email "kiaora@salty.cool"
        
    - name: Install wget
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Setup download directory
      run: |
        mkdir -p ./apt-repos

    - name: Download APT repository files one by one
      run: |
        # List of base URLs for Debian and Ubuntu repositories (adjust for your needs)
        BASE_URLS=(
          "http://deb.debian.org/debian/dists/stable/main/binary-amd64/"
          "http://archive.ubuntu.com/ubuntu/dists/focal/main/binary-amd64/"
        )
        
        # Loop through each base URL (Debian/Ubuntu repositories)
        for BASE_URL in "${BASE_URLS[@]}"; do
          # Use wget to recursively download all .deb files (ensure only .deb files are downloaded)
          wget -r -np -nH --cut-dirs=3 -A "*.deb" -P ./apt-repos "$BASE_URL"
        done

    - name: Push downloaded .deb files to GitHub
      run: |
        # Add all downloaded .deb files
        git add ./apt-repos/**/*.deb
        
        # Commit and push the changes
        git commit -m "Add .deb files from APT repositories"
        git push origin HEAD
