name: Download and Push All APT .deb Files One by One

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install wget
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Setup download directory
      run: |
        mkdir -p ./apt-repos

    - name: Download APT repository files one by one
      run: |
        # List of base URLs for Debian and Ubuntu repositories (adjust for your needs)
        BASE_URLS=(
          "http://deb.debian.org/debian/dists/stable/main/binary-amd64/"
          "http://archive.ubuntu.com/ubuntu/dists/focal/main/binary-amd64/"
        )
        
        # Loop through each base URL (Debian/Ubuntu repositories)
        for BASE_URL in "${BASE_URLS[@]}"; do
          # Use wget to recursively download all .deb files
          wget -r -np -nH --cut-dirs=3 -R "index.html*" -P ./apt-repos "$BASE_URL"
          
          # Find all downloaded .deb files and push them one by one
          find ./apt-repos -type f -name "*.deb" | while read file; do
            # Extract filename from the path
            filename=$(basename "$file")
            
            # Add the .deb file to the repository
            git add "$file"
            
            # Commit and push each file one by one
            git commit -m "Add $filename"
            git push origin HEAD
          done
        done
