name: Generate and Split URL List

on:
  workflow_dispatch: # Allows manual trigger of this workflow

jobs:
  generate-batches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install apt-mirror
        run: sudo apt-get update && sudo apt-get install -y apt-mirror

      - name: Create apt-mirror directories and configuration
        run: |
          sudo mkdir -p /apt-mirror-cache/var/spool/apt-mirror
          sudo mkdir -p /apt-mirror-cache/var
          sudo mkdir -p /apt-mirror-cache/skel
          echo "
          set base_path /apt-mirror-cache
          set mirror_path /apt-mirror-cache/var/spool/apt-mirror
          set skel_path /apt-mirror-cache/skel
          set var_path /apt-mirror-cache/var
          set clean_interval daily
          set nthreads 20
          set _tilde 0
          
          deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
          " | sudo tee /apt-mirror-cache/mirror.list

      - name: Run apt-mirror dry-run
        run: sudo apt-mirror --config=/apt-mirror-cache/mirror.list --dry-run

      - name: Extract URLs from metadata
        run: |
          mkdir -p batch-files
          grep -oP 'http.*\.deb' /apt-mirror-cache/var/spool/apt-mirror/mirror/*/dists/*/binary-*/Packages > urls.txt
          echo "Generated URLs list: $(wc -l urls.txt) entries"

      - name: Split URLs into batches of 1,000
        run: |
          split -l 1000 urls.txt batch-files/batch_
          echo "Split URLs into $(ls batch-files | wc -l) batches"

      - name: Commit and push batch files
        run: |
          mkdir -p batches
          mv batch-files/* batches/
          git config user.name "SaltyBot[bot]"
          git config user.email "bots@salty.cool"
          git add batches/
          git commit -m "indexxed"
          git push
